### ISSUE TITLE
.DS_Store to .gitignore

### ISSUE THREAD

**Issue by lauterry** [yearofmoo/ngMidwayTester#1]
Hi

Not a big deal but you should put .DS_Store into the .gitignore file :)

By the way, Excellent article on testing with AngularJS and Testacular

http://www.yearofmoo.com/2013/01/full-spectrum-testing-with-angularjs-and-testacular.html

Best regards

**Comment by matsko** [comment]
Thanks for the heads up :) I've been meaning to get around to document and beef up this tool.
